openapi: 3.1.0
info:
  title: eth_chainId - optimism
  version: '1.0'
servers:
  - url: 'https://opt-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_chainId.yaml#/components/pathItems/path/post
      operationId: eth-chainid-optimism
