openapi: 3.1.0
info:
  title: eth_protocolVersion - optimism
  version: '1.0'
servers:
  - url: 'https://opt-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_protocolVersion.yaml#/components/pathItems/path/post
      operationId: eth-protocolversion-optimism
