openapi: 3.1.0
info:
  title: eth_getUncleByBlockNumberAndIndex - arbitrum
  version: '1.0'
servers:
  - url: 'https://arb-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      operationId: eth-getunclebyblocknumberandindex-arbitrum
      $ref: ../ethereum/eth_getUncleByBlockNumberAndIndex.yaml#/components/pathItems/path/post
