openapi: 3.1.0
info:
  title: eth_newBlockFilter - arbitrum
  version: '1.0'
servers:
  - url: 'https://arb-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      operationId: eth-newblockfilter-arbitrum
      $ref: ../ethereum/eth_newBlockFilter.yaml#/components/pathItems/path/post
