openapi: 3.1.0
info:
  title: eth_sendRawTransaction - arbitrum
  version: '1.0'
servers:
  - url: 'https://arb-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      operationId: eth-sendrawtransaction-arbitrum
      $ref: ../ethereum/eth_sendRawTransaction.yaml#/components/pathItems/path/post
      x-readme:
        samples-languages:
          - javascript
          - curl
          - python
          - go
        code-samples:
          - language: javascript
            name: Alchemy SDK
            code: |
              import { Network, Alchemy, Wallet, Utils } from "alchemy-sdk";
              import dotenv from "dotenv";
              dotenv.config();

              const { API_KEY, PRIVATE_KEY } = process.env;

              const settings = {
                apiKey: API_KEY,
                network: Network.ARB_MAINNET, // Replace with your network.
              };

              const alchemy = new Alchemy(settings);
              const wallet = new Wallet(PRIVATE_KEY);

              const transaction = {
                to: "0xa238b6008Bc2FBd9E386A5d4784511980cE504Cd",
                value: Utils.parseEther("0.001"),
                gasLimit: "21000",
                maxPriorityFeePerGas: Utils.parseUnits("5", "gwei"),
                maxFeePerGas: Utils.parseUnits("20", "gwei"),
                nonce: await alchemy.core.getTransactionCount(wallet.getAddress()),
                type: 2,
                chainId: 42161, // Corresponds to ARB_MAINNET
              };

              const rawTransaction = await wallet.signTransaction(transaction);
              await alchemy.transact.sendTransaction(rawTransaction);