openapi: 3.1.0
info:
  title: web3_clientVersion - arbitrum
  version: '1.0'
servers:
  - url: 'https://arb-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      operationId: web3-clientversion-arbitrum
      $ref: ../ethereum/web3_clientVersion.yaml#/components/pathItems/path/post
