openapi: 3.1.0
info:
  title: eth_getBlockReceipts
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.g.alchemy.com/v2 '
paths:
  /{apiKey}:
    post:
      summary: eth_getBlockReceipts
      description: Get all transaction receipts for a given block on Ethereum.
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: demo
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../evm_body.yaml#/eth_getBlockReceipts
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: ../evm_responses.yaml#/eth_getBlockReceipts
      operationId: eth-getBlockReceipts
