openapi: 3.1.0
info:
  title: eth_getUncleCountByBlockHash
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.g.alchemy.com/v2 '
paths:
  /{apiKey}:
    $ref: '#/components/pathItems/path'
components:
  pathItems:
    path:
      post:
        summary: eth_getUncleCountByBlockHash
        description: Returns the number of uncles in a block matching the given block hash.
        tags: []
        parameters:
          - name: apiKey
            in: path
            schema:
              type: string
              default: demo
            required: true
        requestBody:
          content:
            application/json:
              schema:
                $ref: ../evm_body.yaml#/eth_getUncleCountByBlockHash
        responses:
          '200':
            description: Returns integer of the number of uncles in this block.
            content:
              application/json:
                schema:
                  $ref: ../evm_responses.yaml#/string_result_response
        operationId: eth-getUncleCountByBlockHash
