openapi: 3.1.0
info:
  title: Trace Get
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.g.alchemy.com/v2 '
paths:
  /{apiKey}:
    post:
      summary: trace_get
      description: Returns trace at given position.
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: demo
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../evm_body.yaml#/trace_get
      responses:
        '200':
          description: 'Returns - Trace object.'
          content:
            application/json:
              schema:
                $ref: ../evm_responses.yaml#/trace_get
      operationId: trace-get
