openapi: 3.1.0
info:
  title: getAccountInfo
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: getAccountInfo
      description: Returns all information associated with the account of provided Pubkey.
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: demo
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: solana_body.yaml#/getAccountInfo
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: solana_responses.yaml#/getAccountInfo
      operationId: getAccountInfo
      x-readme:
        explorer-enabled: false
