openapi: 3.1.0
info:
  title: Blocks With Limit
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: getBlocksWithLimit
      description: Returns a list of confirmed blocks starting at the given slot.
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: demo
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: solana_body.yaml#/getBlocksWithLimit
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: solana_responses.yaml#/getBlocks
      operationId: getBlocksWithLimit
      x-readme:
        explorer-enabled: false
