openapi: 3.1.0
info:
  title: Max Shred Insert Slot
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: getMaxShredInsertSlot
      description: Get the max slot seen from after shred insert..
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: demo
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: solana_body.yaml#/getMaxShredInsertSlot
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: solana_responses.yaml#/getMaxRetransmitSlot
      operationId: getMaxShredInsertSlot
