openapi: 3.1.0
info:
  title: Token Supply
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: getTokenSupply
      description: Returns the total supply of an SPL Token type.
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: demo
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: solana_body.yaml#/getTokenSupply
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: solana_responses.yaml#/getTokenSupply
      operationId: getTokenSupply
      x-readme:
        explorer-enabled: false
