openapi: 3.1.0
info:
  title: Token Account Balance
  version: '1.0'
servers:
  - url: 'https://solana-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      summary: getTokenAccountBalance
      description: Returns the token balance of an SPL Token account..
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: demo
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: solana_body.yaml#/getTokenAccountBalance
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: solana_responses.yaml#/getTokenAccountBalance
      operationId: getTokenAccountBalance
      x-readme:
        explorer-enabled: false
