openapi: 3.1.0
info:
  title: eth_getBlockTransactionCountByHash - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      description: Returns the number of transactions in a block matching the given block hash on Polygon.
      $ref: ../ethereum/eth_getBlockTransactionCountByHash.yaml#/components/pathItems/path/post
      operationId: eth-getblocktransactioncountbyhash-polygon
