openapi: 3.1.0
info:
  title: eth_createAccessList - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      description: 'Polygon API - Creates an EIP2930 type `accessList` based on a given Transaction object. Returns list of addresses and storage keys that are read and written by the transaction (except the sender account and precompiles), plus the estimated gas consumed when the access list is added.'
      $ref: ../ethereum/eth_createAccessList.yaml#/components/pathItems/path/post
      operationId: eth-createaccesslist-polygon