openapi: 3.1.0
info:
  title: eth_getTransactionByBlockNumberAndIndex - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      description: Returns information about a transaction by block number and transaction index position on Polygon.
      $ref: ../ethereum/eth_getTransactionByBlockNumberAndIndex.yaml#/components/pathItems/path/post
      operationId: eth-gettransactionbyblocknumberandindex-polygon
