openapi: 3.1.0
info:
  title: eth_getUncleByBlockNumberAndIndex - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      description: Returns information about an uncle of a block by number and uncle index position on Polygon.
      $ref: ../ethereum/eth_getUncleByBlockNumberAndIndex.yaml#/components/pathItems/path/post
      operationId: eth-getunclebyblocknumberandindex-polygon
