openapi: 3.1.0
info:
  title: eth_chainId - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      description: 'Returns the currently configured chain ID on Polygon, a value used in replay-protected transaction signing as introduced by EIP-155.'
      $ref: ../ethereum/eth_chainId.yaml#/components/pathItems/path/post
      operationId: eth-chainid-polygon
