openapi: 3.1.0
info:
  title: eth_uninstallFilter - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      description: Polygon API - Uninstalls a filter with given id. Should always be called when watch is no longer needed. Additionally, Filters timeout when they aren’t requested with eth_getFilterChangesfor a period of time.
      $ref: ../ethereum/eth_uninstallFilter.yaml#/components/pathItems/path/post
      operationId: eth-uninstallfilter-optimism