openapi: 3.1.0
info:
  title: eth_getUncleCountByBlockNumber - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      description: Returns the number of uncles in a block matching the given block number on Polygon.
      $ref: ../ethereum/eth_getUncleCountByBlockNumber.yaml#/components/pathItems/path/post
      operationId: eth-getunclecountbyblocknumber-polygon
