openapi: 3.1.0
info:
  title: eth_getProof - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      description: Returns the account and storage values of the specified account including the Merkle-proof on Polygon. This call can be used to verify that the data you are pulling from is not tampered with.
      $ref: ../ethereum/eth_getProof.yaml#/components/pathItems/path/post
      operationId: eth-getproof-polygon
      x-readme:
        explorer-enabled: false
