openapi: 3.1.0
info:
  title: eth_getProof - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_getProof.yaml#/components/pathItems/path/post
      operationId: eth-getproof-polygon
      x-readme:
        explorer-enabled: false
