openapi: 3.1.0
info:
  title: eth_blockNumber - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_blockNumber.yaml#/components/pathItems/path/post
      description: Returns the number of the most recent block on Polygon.
      x-readme:
        samples-languages:
          - javascript
          - curl
          - python
          - go
        code-samples:
          - language: javascript
            name: Alchemy SDK
            code: |
              // Setup: npm install alchemy-sdk
              // Github: https://github.com/alchemyplatform/alchemy-sdk-js
              import { Network, Alchemy } from "alchemy-sdk";

              // Optional Config object, but defaults to demo api-key and eth-mainnet.
              const settings = {
                apiKey: "demo", // Replace with your Alchemy API Key.
                network: Network.MATIC_MAINNET, // Replace with your network.
              };
              const alchemy = new Alchemy(settings);

              // Get the latest block number
              alchemy.core.getBlockNumber().then(console.log);
      responses:
          '200':
            description: Returns integer of the current block number the client is on.
            content:
              application/json:
                schema:
                  $ref: ../evm_responses.yaml#/eth_blockNumber