openapi: 3.1.0
info:
  title: eth_getBalance - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_getBalance.yaml#/components/pathItems/path/post
      operationId: eth-getbalance-polygon
      description: Returns the balance of the account of a given address on Polygon.
      x-readme:
        samples-languages:
          - javascript
          - curl
          - python
          - go
        code-samples:
          - language: javascript
            name: Alchemy SDK
            code: |
              // Setup: npm install alchemy-sdk
              // Github: https://github.com/alchemyplatform/alchemy-sdk-js
              import { Network, Alchemy } from "alchemy-sdk";

              // Optional config object, but defaults to demo api-key and eth-mainnet.
              const settings = {
                apiKey: "demo", // Replace with your Alchemy API Key.
                network: Network.MATIC_MAINNET, // Replace with your network.
              };
              const alchemy = new Alchemy(settings);

              alchemy.core.getBalance("vitalik.eth", "latest").then(console.log);
