openapi: 3.1.0
info:
  title: web3_sha3 - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      description: Returns Keccak-256 (not the standardized SHA3-256) of the given data on Polygon.
      $ref: ../ethereum/web3_sha3.yaml#/components/pathItems/path/post
      operationId: web3-sha3-polygon