openapi: 3.1.0
info:
  title: web3_clientVersion - Polygon
  version: '1.0'
servers:
  - url: 'https://polygon-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      description: Returns the current client version on Polygon.
      $ref: ../ethereum/web3_clientVersion.yaml#/components/pathItems/path/post
      operationId: web3-clientVersion-polygon