openapi: 3.1.0
info:
  title: eth_cancelPrivateTransaction
  version: '1.0'
servers:
  - url: 'https://eth-mainnet.g.alchemy.com/v2 '
paths:
  /{apiKey}:
    post:
      operationId: eth-cancelPrivateTransaction
      summary: eth_cancelPrivateTransaction
      description: Request to cancel private transactions on Ethereum that are sent via eth_sendPrivateTransaction.
      tags: []
      parameters:
        - name: apiKey
          in: path
          schema:
            type: string
            default: demo
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../evm_body.yaml#/eth_cancelPrivateTransaction
      responses:
        '200':
          description: 'Returns true if transaction was successfully cancelled, false if not.'
          content:
            application/json:
              schema:
                $ref: ../evm_responses.yaml#/eth_cancelPrivateTransaction
