openapi: 3.1.0
info:
  title: eth_accounts - astar
  version: '1.0'
servers:
  - url: 'https://astar-mainnet.g.alchemy.com/v2/'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_accounts.yaml#/components/pathItems/path/post
      operationId: eth-accounts-astar
