openapi: 3.1.0
info:
  title: eth_getTransactionByHash - astar
  version: '1.0'
servers:
  - url: 'https://astar-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/eth_getTransactionByHash.yaml#/components/pathItems/path/post
      operationId: eth-gettransactionbyhash-astar
      x-readme:
        samples-languages:
          - javascript
          - curl
          - python
          - go
        code-samples:
          - language: javascript
            name: Alchemy SDK
            code: |
              // Setup: npm install alchemy-sdk
              // Github: https://github.com/alchemyplatform/alchemy-sdk-js
              import { Network, Alchemy } from "alchemy-sdk";

              // Optional config object, but defaults to demo api-key and eth-mainnet.
              const settings = {
                apiKey: "demo", // Replace with your Alchemy API Key.
                network: Network.ASTAR_MAINNET, // Replace with your network.
              };
              const alchemy = new Alchemy(settings);

              alchemy.core
                .getTransaction(
                  "0x88df016429689c079f3b2f6ad39fa052532c56795b733da78a91ebe6a713944b"
                )
                .then(console.log);
