openapi: 3.1.0
info:
  title: web3_clientVersion - astar
  version: '1.0'
servers:
  - url: 'https://astar-mainnet.g.alchemy.com/v2'
paths:
  /{apiKey}:
    post:
      $ref: ../ethereum/web3_clientVersion.yaml#/components/pathItems/path/post
      operationId: web3-clientVersion-astar
